name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the package
        run: |
          make install
      - name: Install test dependencies
        run: |
          make install-test
      - name: Test
        run: |
          make test
      - name: Benchmark
        run: |
          make benchmark
